// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417213708_RefactoredFullTitle")]
    partial class RefactoredFullTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantEntity", b =>
                {
                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GlobalProductId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GlobalVariantId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<long>("VariantId")
                        .HasColumnType("bigint");

                    b.HasKey("ShopifyProductVariantId");

                    b.HasIndex("GlobalVariantId")
                        .IsUnique();

                    b.ToTable("ShopifyProductVariants", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantLogEventEntity", b =>
                {
                    b.Property<Guid>("ShopifyProductVariantLogEventId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("ShopifyProductVariantLogEventId");

                    b.HasIndex("ShopifyProductVariantId");

                    b.ToTable("ShopifyProductVariantLogEvents", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemEntity", b =>
                {
                    b.Property<Guid>("SkulabsItemId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkulabsSourceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("SkulabsItemId");

                    b.HasIndex("SkulabsSourceId")
                        .IsUnique();

                    b.ToTable("SkulabsItems", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantLogEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ShopifyProductVariantEntity", "ShopifyProductVariant")
                        .WithMany("LogEvents")
                        .HasForeignKey("ShopifyProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopifyProductVariant");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemEntity", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ShopifyProductVariantEntity", "ShopifyProductVariant")
                        .WithOne("SkulabsItem")
                        .HasForeignKey("Infrastructure.Database.Entities.SkulabsItemEntity", "SkulabsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopifyProductVariant");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantEntity", b =>
                {
                    b.Navigation("LogEvents");

                    b.Navigation("SkulabsItem");
                });
#pragma warning restore 612, 618
        }
    }
}
