// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808164520_AddVariantRawTitles")]
    partial class AddVariantRawTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Database.Entities.DesiredItemStateEntity", b =>
                {
                    b.Property<Guid>("DesiredItemStateId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Location")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.HasKey("DesiredItemStateId");

                    b.HasIndex("ShopifyProductVariantId")
                        .IsUnique();

                    b.ToTable("DesiredItemStates", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantEntity", b =>
                {
                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime>("DeletedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("'-infinity'::timestamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FailedShopifySyncAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("GlobalProductId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GlobalVariantId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PendingShopifySync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<long>("VariantId")
                        .HasColumnType("bigint");

                    b.Property<string>("VariantTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("");

                    b.HasKey("ShopifyProductVariantId");

                    b.HasIndex("GlobalVariantId")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasFilter("\"IsActive\" = true AND \"IsDeleted\" = false");

                    b.HasIndex("PendingShopifySync")
                        .HasFilter("\"PendingShopifySync\" = true");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId")
                        .IsUnique();

                    b.ToTable("ShopifyProductVariants", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantLogEventEntity", b =>
                {
                    b.Property<Guid>("ShopifyProductVariantLogEventId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ShopifyProductVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("ShopifyProductVariantLogEventId");

                    b.HasIndex("ShopifyProductVariantId");

                    b.ToTable("ShopifyProductVariantLogEvents", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemEntity", b =>
                {
                    b.Property<Guid>("SkulabsItemId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FailedSkulabsSyncAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("FirstSeenUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime>("LastSeenUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Location")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("PendingSkulabsSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkulabsSourceItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("SkulabsItemId");

                    b.HasIndex("PendingSkulabsSync")
                        .HasFilter("\"PendingSkulabsSync\" = true");

                    b.HasIndex("SkulabsSourceItemId")
                        .IsUnique();

                    b.ToTable("SkulabsItems", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemListingEntity", b =>
                {
                    b.Property<Guid>("SkulabsItemListingId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("RawVariantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShopifyProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ShopifyProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkulabsItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkulabsSourceListingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SkulabsItemListingId");

                    b.HasIndex("ShopifyProductVariantId");

                    b.HasIndex("SkulabsItemId");

                    b.HasIndex("SkulabsSourceListingId")
                        .IsUnique();

                    b.ToTable("SkulabsItemListings", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.DesiredItemStateEntity", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ShopifyProductVariantEntity", "ShopifyProductVariant")
                        .WithOne("DesiredState")
                        .HasForeignKey("Infrastructure.Database.Entities.DesiredItemStateEntity", "ShopifyProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopifyProductVariant");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantLogEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ShopifyProductVariantEntity", "ShopifyProductVariant")
                        .WithMany("LogEvents")
                        .HasForeignKey("ShopifyProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopifyProductVariant");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemListingEntity", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ShopifyProductVariantEntity", "ShopifyProductVariant")
                        .WithMany("SkulabsItemListings")
                        .HasForeignKey("ShopifyProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Infrastructure.Database.Entities.SkulabsItemEntity", "SkulabsItem")
                        .WithMany("Listings")
                        .HasForeignKey("SkulabsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopifyProductVariant");

                    b.Navigation("SkulabsItem");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ShopifyProductVariantEntity", b =>
                {
                    b.Navigation("DesiredState");

                    b.Navigation("LogEvents");

                    b.Navigation("SkulabsItemListings");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.SkulabsItemEntity", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
