services:
  web.api:
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__SkuSync: "Host=postgres;Port=5432;Database=skusync;Username=postgres;Password=password;Include Error Detail=true"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
  
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password